# Generated by Django 2.2.1 on 2019-06-09 22:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0008_auto_20190527_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='client_rating',
            field=models.IntegerField(blank=True, default='5', null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='tutor_rating',
            field=models.IntegerField(blank=True, default='5', null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(blank=True, default='default-profile.png', null=True, upload_to='profile_image'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_image', to=settings.AUTH_USER_MODEL),
        ),
    ]
