# Generated by Django 2.2.1 on 2019-05-17 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_auto_20190516_0027'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='year',
            field=models.CharField(blank=True, default='blank', max_length=40),
        ),
    ]
