# Generated by Django 2.2.1 on 2019-05-27 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0006_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='profile_image',
        ),
        migrations.AddField(
            model_name='photo',
            name='profile_image',
            field=models.ImageField(blank=True, default='default-profile.png', upload_to='profile_image'),
        ),
    ]
